### ISSUE TITLE
pre-compiled version?

### ISSUE THREAD

**Issue by VisoXC** [DedInc/DiscordTokenGrabber#5]
i have problems compiling the file. i read the issues and heard there are instructions in the readme file. there wasn't.

it tried:

`gradlew build`
`gradle build`

but neither worked. i gotta add that i'm very bad with java so that maybe the issue, help would be nice though, still.

edit: could you maybe put a pre-compiled version in the releases?

**Comment by DedInc** [comment]
use

```sh
gradlew shadowJar
```

**Comment by VisoXC** [comment]
That command didn't work either.
